name: Deploy to Heroku

on:
  push:
    branches: [ main, master, staging ]
  pull_request:
    branches: [ main, master, staging ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Build executable JAR
        run: ./gradlew bootJar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/libs/*.jar

  deploy-staging:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug branch information
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub event name: ${{ github.event_name }}"
          echo "Is staging branch: ${{ github.ref == 'refs/heads/staging' }}"

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: build/libs

      - name: List downloaded files
        run: ls -la build/libs

      - name: Deploy to Heroku (Staging)
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_STAGING_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false
          justlogin: false

  deploy-production:
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Debug branch information
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub event name: ${{ github.event_name }}"
          echo "Is main branch: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}"

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: build/libs

      - name: List downloaded files
        run: ls -la build/libs

      - name: Deploy to Heroku (Production)
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_PRODUCTION_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false
          justlogin: false