name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
      - kupon
  pull_request:
    branches:
      - main
      - kupon

permissions:
  contents: read

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up Java Toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
