name: Unit Test
on:
  push:
    branches: [ staging, auth, kupon, payment, pengelolaan_kos, penyewaan_kos, wishlist]
  pull_request:
    branches: [ staging, auth, kupon, payment, pengelolaan_kos, penyewaan_kos, wishlist]

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up Java Toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Add gradlew permission
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test